#!/bin/sh -eu

SED='s|\\(%s\\)\\.o[ :]*|%s\\1.o %s: \\\\\\
|
s/^[ ]*//'

parse_arguments() {
    compile=
    dir=
    files=
    output=
    suffix=.d

    while getopts c:d:f:o:s: opt; do
        case $opt in
            (c)
                compile="$OPTARG"
                ;;
	    (d)
                parse_dir
	        ;;
	    (f)
	        files="$OPTARG"
	        ;;
	    (o)
                parse_output
                ;;
	    (s)
	        suffix="$OPTARG"
	        ;;
	    (\?)
	        exit 2
	        ;;
        esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 1 ]; then
        printf '%s: Too many arguments\n' "$script" >&2
        exit 2
    elif [ $# -lt 1 ]; then
        if [ -z "$output" ]; then
            printf '%s: Not enough arguments\n' "$script" >&2
            exit 2
        else
            dir="$(dirname "$output" | sed 's|^\./||')"
            stem="$(basename "$output" | cut -d. -f 1)"
        fi
    else
        stem="$1"
    fi

    output="${output:-${dir:+$dir/}$stem$suffix}"
}

parse_dir() {
    if [ ! -d "$OPTARG" ]; then
        printf '%s: "%s": No such directory\n' \
               "$script" "$OPTARG" >&2
        exit 2
    elif [ "$output" ]; then
        printf '%s: Argument "-d %s" conflicts with argument "-o %s"\n' \
               "$script" "$OPTARG" "$output" >&2
        exit 2
    else
	dir="$OPTARG"
    fi
}

parse_output() {
    if [ ! -d "$(dirname "$OPTARG")" ]; then
        printf '%s: "%s": No such directory\n' \
               "$script" "$(dirname $OPTARG)" >&2
        exit 2
    elif [ "$dir" ]; then
        printf '%s: Argument "-o %s" conflicts with argument "-d %s"\n' \
               "$script" "$OPTARG" "$dir" >&2
        exit 2
    else
	output="$OPTARG"
    fi
}

sed_makefile() {
    sed "$(printf "$SED\n" "$stem" "${dir:+$dir/}" "$output${files:+ $files}")"
}

script="$(basename "$0")"

parse_arguments "$@"

exec >"$output"

if [ -n "$compile" ]; then
    $compile | sed_makefile
else
    sed_makefile
fi
