#!/bin/sh -eu

# Copyright (C) 2025  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

install_symlinks() (
    cd "$(dirname "$1")"
    file=$(basename "$1")
    stem=${file%.*.*.*}
    alias=$file

    until [ "$alias" = "$stem" ]; do
	alias=${alias%.*}
	ln -sf "$file" "$alias"
    done
)

parse_arguments() {
    while getopts h opt; do
	case $opt in
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -lt 2 ]; then
       usage_error
    fi

    library="$1"
}

usage() {
    cat <<EOF >&2
Usage: $script LIBRARY
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script="$(basename "$0")"

parse_arguments "$@"

if [ -f "$library" ]; then
    case "$library" in
	(*/lib*.so.*|lib*.so.*)
	    install_symlinks "$library"
	    ;;
	(*)
	    usage_error
	    ;;
    esac
else
    usage_error
fi
