#!/bin/sh -eu

# Copyright (C) 2025  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BINARY_DIR=bin
INCLUDE_DIR=include
LIBRARY_DIR=lib

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
}

configure_platform() {
    install=$(get_installer)
    libraries=$(get_libraries)
    programs=$(get_programs)
}

get_installer() {
    case "$(uname)" in
	(Darwin)
	    printf '%s\n' ginstall
	    ;;
	(*)
	    printf '%s\n' install
	    ;;
    esac
}

get_libraries() {
    find $LIBRARY_DIR -type f '(' -name 'lib*.a' -o -name 'lib*.so.*' ')'
}

get_programs() {
    find $BINARY_DIR -type f ! -name '*.map'
}

install_files() {
    $install -d $PREFIX/include/network $PREFIX/lib $PREFIX/bin
    $install -m 644 $INCLUDE_DIR/$platform/network/* \
	     $PREFIX/include/network
    $install -m 644 $INCLUDE_DIR/network/* \
	     $PREFIX/include/network
    $install $libraries $PREFIX/lib
    $install $programs $PREFIX/bin
}

install_package() {
    install_files
    install_symlinks $libraries
}

install_symlinks() {
    "${script_prefix}install-symlinks" "$@"
}

parse_arguments() {
    platform=unix

    while getopts p:h opt; do
	case $opt in
	    (p)
		platform="$OPTARG"
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))
}

usage() {
    cat <<EOF >&2
Usage: $script [-p platform]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script="$(basename "$0")"

case "$0" in
    (*/*)
	script_dir=$(cd "$(dirname "$0")" && pwd)
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

parse_arguments "$@"
configure_platform
install_package
