#!/bin/sh -eu

# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

SED='1s|\\(%s\\)\\(\\.[a-z][a-z]*\\)[ :]*|%s\\1\\2 %s%s: \\\\\\
|
s|^[ ]*||'

make_makefile() {
    exec >"$output"
    files="${files:+$files }$output"

    if [ -n "$command" ]; then
	$command | sed_makefile
    else
	sed_makefile
    fi
}

parse_arguments() {
    command=
    files=
    object_dir=
    output=

    while getopts c:d:f:o:h opt; do
	case $opt in
	    (c)
		command="$OPTARG"
		;;
	    (d)
		object_dir="$OPTARG"
		;;
	    (f)
		files="${files+$files }$OPTARG"
		;;
	    (o)
		parse_output
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ -z "$output" ]; then
	output="$1"
	shift
    fi

    files="$@"
}

parse_object_dir() {
    object_dir="$OPTARG"
}

parse_output() {
    output_dir=$(dirname "$OPTARG")
    if [ ! -d "$output_dir" ]; then
	usage_error '%s: "%s": No such directory\n' "$script" "$output_dir"
	exit 2
    else
	output="$OPTARG"
	stem="$(basename "$output" .dep)"
    fi
}

sed_makefile() {
    sed "$(printf "$SED\n" "$stem" "${object_dir:+$object_dir/}" "$files")"
}

usage() {
    cat <<EOF >&2
Usage: $script [-c COMMAND] [-d OBJECT_DIR] [-o OUTPUT] [OUTPUT] [FILE [...]]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script="$(basename "$0")"

parse_arguments "$@"
make_makefile
