#!/bin/sh -eu

# Copyright (C) 2025  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

get_make_command() {
    case "$(uname -s)" in
        (*BSD|Darwin)
	    printf '%s\n' gmake
	    ;;
        (*)
	    printf '%s\n' make
	    ;;
    esac
}

make_package() {
    make=$(get_make_command)

    if printf '%s\n' "$1" | grep -Eq '^(Debug|Release)$'; then
	$make BUILD_TYPE="$1" WITH_COVERAGE=false clean package
    fi
}

make_package "${@:-Release}"
