#!/bin/sh -eu

parse_arguments() {
    args=

    while getopts vh opt; do
	case $opt in
	    (v)
		args=-v
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ $# -gt 0 ]; then
	usage_error '%s: Too many arguments\n' "$script"
    fi
}

run_unix_program() (
    case "$1" in
	(*/unix-client)
	    # cd "$dirname"
	    "$1"${args:+ $args} 2 2
	    "$1"${args:+ $args} DOWN
	    ;;
	(*/unix-server)
	    # cd "$dirname"
	    "$1"${args:+ $args}
	    ;;
	(*)
	    ;;
    esac
)

run_unix_programs() {
    run_unix_program bin/unix-server &
    sleep 1
    run_unix_program bin/unix-client
}

usage() {
    cat <<EOF >&2
Usage: $script [-v]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")
parse_arguments "$@"
run_unix_programs
