#!/bin/sh -eu

run_test_program() (
    basename="$(basename "$filename" .exe)"
    dirname="$(dirname "$filename")"
    logname="$basename.log"
    cd "$dirname"
    ${valgrind:+$valgrind }"./$basename" >"$logname"
)

export HOSTNAME=${HOSTNAME-$(hostname)}
export LD_LIBRARY_PATH=".${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"

if [ "$USING_VALGRIND" = true ]; then
   valgrind=valgrind
else
   valgrind=
fi

for filename in "$@"; do
    run_test_program "$filename"
done
