#!/bin/sh -eu

# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

run_unix_program() (
    basename=$(basename "$1" .exe)
    dirname=$(dirname "$1")
    program="$dirname/$basename"

    case "$basename" in
	(unix-client)
	    sleep 1
	    "$program"${args:+ $args} 2 2
	    "$program"${args:+ $args} DOWN
	    ;;
	(unix-server)
	    "$program"${args:+ $args} &
	    ;;
	(*)
	    ;;
    esac
)

run_unix_programs() {
    args=

    while getopts vh opt; do
	case $opt in
	    (v)
		args=-v
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    for file in $(printf '%s\n' "$@" | sort -r); do
	run_unix_program "$file"
    done
}

usage() {
    cat <<EOF >&2
Usage: $script [-v]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")

run_unix_programs "$@"
