#!/bin/sh -eu

run_test_program() (
    export LD_LIBRARY_PATH=".${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
    basename="$(basename "$filename" .exe)"
    dirname="$(dirname "$filename")"
    logname="$basename.log"
    cd "$dirname"
    "./$basename" >"$logname"
)

export HOSTNAME=${HOSTNAME-$(hostname)}

for filename in "$@"; do
    run_test_program "$filename"
done
