#!/bin/sh -eu

run_test_program() (
    case "$1" in
	(*/test-*)
	    ${valgrind:+$valgrind }"$1" >"$(basename ${1%.exe}.log)"
	    ;;
	(*)
	    ;;
    esac
)

run_test_programs() {
    if [ "${USING_VALGRIND-}" = true ]; then
	valgrind="valgrind -q"
    else
	valgrind=
    fi

    for filename in "$@"; do
	run_test_program "$filename"
    done
}

run_test_programs "$@"
