#!/bin/sh -eu

# Copyright (C) 2022  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

run_program() {
    basename=$(basename "$1" .exe)
    dirname=$(dirname "$1")
    filename="$dirname/$basename"
    shift

    case "$basename" in
	(test-*)
	    if ! ${wrapper:+$wrapper }$filename "$@" >"$filename.log"; then
		printf '%s\n' "Program $basename returned a non-zero exit code"
		errors=$(expr $errors + 1)
	    fi
	    ;;
	(unix-client)
	    ("$filename" "$@" 1 2 3 4;
	     "$filename" "$@" DOWN) >"$filename.log"
	    sleep 1
	    ;;
	(unix-server)
	    "$filename" "$@" >"$filename.log" &
	    sleep 1
	    ;;
    esac
}

run_programs() {
    args=
    dir=
    errors=0

    if [ "${USING_VALGRIND-}" = true ]; then
	wrapper="valgrind -q"
    else
	wrapper=
    fi

    while getopts d:rvh opt; do
	case $opt in
	    (d)
		dir="$OPTARG"
		;;
	    (v)
		args=-v
		;;
	    (h)
		usage
		exit 0
		;;
	    (\?)
		exit 2
		;;
	esac
    done

    shift $(($OPTIND - 1))

    if [ -n "$dir" -a "$dir" != "." ]; then
	cd "$dir"
    fi

    for program; do
	run_program "$program"
    done

    if [ "$errors" -ne 0 ]; then
	exit 1
    fi

    if [ -n "$args" ]; then
	for program; do
	    run_program "$program" $args
	done
    fi
}

usage() {
    cat <<EOF >&2
Usage: $script [-d DIRECTORY] [-v]
       $script -h
EOF
}

usage_error() {
    if [ $# -gt 0 ]; then
	printf "$@" >&2
    fi

    printf '%s\n' '' >&2
    usage
    exit 2
}

script=$(basename "$0")

run_programs "$@"
